  <h1><?php echo $this->escape($this->title);?></h1>
  <div id="description">
    <?php echo $this->escape($this->description);?>
  </div>

  <form name="edit" method="post" action="<?php echo $this->escape($this->action)?>">
  
  <input type="hidden" name="id" value="<?php echo $this->data->id?>">
  <table>
    <tr>
	  <td><?php echo $this->escape($this->label_uname)?></td>
	  <td><input type="text" name="username" value="<?php echo $this->data->username?>"></td>
	</tr>
    <tr>
	  <td><?php echo$this->escape($this->label_pass)?></td>
	  <td><input type="password" name="password" value="<?php echo $this->data->password?>"></td>
	</tr>	
	<tr>
	  <td><?php echo $this->escape($this->label_fname)?></td>
	  <td><input type="text" name="firstname" value="<?php echo $this->data->firstname?>"></td>
	</tr>	
	<tr>
	  <td><?php echo $this->escape($this->label_lname)?></td>
	  <td><input type="text" name="lastname" value="<?php echo $this->data->lastname?>"></td>
	</tr>	
  </table>
  <input type="submit" name="submit" value="<?php echo $this->escape($this->label_submit);?>">
  
        
  </form>
  
  