  <h1><?=$this->escape($this->title);?></h1>
  <div id="description">
    <?=$this->escape($this->description);?>
  </div>

  <form name="edit" method="post" action="<?=$this->escape($this->action)?>">
  
  <input type="hidden" name="id" value="<?=$this->data->id?>">
  <table>
    <tr>
	  <td><?=$this->escape($this->label_uname)?></td>
	  <td><input type="text" name="username" value="<?=$this->data->username?>"></td>
	</tr>
    <tr>
	  <td><?=$this->escape($this->label_pass)?></td>
	  <td><input type="password" name="password" value="<?=$this->data->password?>"></td>
	</tr>	
	<tr>
	  <td><?=$this->escape($this->label_fname)?></td>
	  <td><input type="text" name="firstname" value="<?=$this->data->firstname?>"></td>
	</tr>	
	<tr>
	  <td><?=$this->escape($this->label_lname)?></td>
	  <td><input type="text" name="lastname" value="<?=$this->data->lastname?>"></td>
	</tr>	
  </table>
  <input type="submit" name="submit" value="<?=$this->escape($this->label_submit);?>">
  
        
  </form>
  
  