  <h1><?php echo $this->translate("user_edit_form"); ?></h1>
  <div id="description">
    <?php echo $this->translate("enter_form_completely"); ?>
  </div>

  <form name="edit" method="post" action="<?php echo $this->escape($this->action)?>">
  
  <input type="hidden" name="id" value="<?php echo $this->data->id?>">
  <table>
    <tr>
	  <td><?php echo $this->translate("username"); ?></td>
	  <td><input type="text" name="username" value="<?php echo $this->data->username?>" readonly="readonly"></td>
	</tr>
    <tr>
	  <td><?php echo $this->translate("password"); ?></td>
	  <td><input type="password" name="password" value=""></td>
	</tr>	
	<tr>
	  <td><?php echo $this->translate("first_name"); ?></td>
	  <td><input type="text" name="firstname" value="<?php echo $this->data->firstname?>"></td>
	</tr>	
	<tr>
	  <td><?php echo $this->translate("last_name"); ?></td>
	  <td><input type="text" name="lastname" value="<?php echo $this->data->lastname?>"></td>
	</tr>	
  </table>
  <input type="submit" name="submit" value="<?php echo $this->translate("save"); ?>">
  
        
  </form>