  <h1><?=$this->escape($this->title);?></h1>
  <h2><?=$this->escape($this->description);?></h2>
  <a href="register">Register</a>
   
  <table border="1">
    <tr>
	  <th>ID</th>
	  <th>Username</th>	  
	  <th>First Name</th>	
	  <th>Last Name</th>	  
	</tr>
 
  <?php foreach ($this->datas as $entry): ?>
  <tr>
	  <td><?=$this->escape($entry->id)?></td>	
	  <td><?=$this->escape($entry->username)?></td>
	  <td><?=$this->escape($entry->firstname)?></td>	  
	  <td><?=$this->escape($entry->lastname)?></td>
	  <td>
	    <a href="edit/id/<?=$this->escape($entry->id)?>">Edit</a>
		|
	    <a href="del/id/<?=$this->escape($entry->id)?>">Delete</a>		
	  </td>	  
	</tr> 
	
        <?php endforeach ?>
  </table>
