  <h1><?php echo $this->escape($this->title);?></h1>
  You have entered this page: <?php echo $this->escape($this->request);?> time(s).
  <form method='post' action='<?php echo $this->escape($this->action);?>'>
  <table>
    <tr>
	  <td><?php echo $this->escape($this->username);?></td>
	  <td><input type='text' name='username'></td>
	</tr>
    <tr>
	  <td><?php echo $this->escape($this->password);?></td>
	  <td><input type='password' name='password'></td>
	</tr>	
  </table>
  <input type='submit' name='login' value='Login'>
  </form>
