  <h1><?php echo $this->translate("new_member_title"); ?></h1>
  
  <form name="register" method="post" action="<?php echo $this->escape($this->action)?>">
  <table>
    <tr>
	  <td><?php echo $this->translate("username"); ?></td>
	  <td><input type="text" name="username"></td>
	</tr>
    <tr>
	  <td><?php echo $this->translate("first_name"); ?></td>
	  <td><input type="text" name=firstname></td>
	</tr>	
	 <tr>
	  <td><?php echo $this->translate("last_name"); ?></td>
	  <td><input type="text" name="lastname"></td>
	</tr>
    <tr>
	  <td><?php echo $this->translate("password"); ?></td>
	  <td><input type="password" name="password"></td>
	</tr>	
  </table>
  <input type="submit" name="submit" value="<?php echo $this->translate("save"); ?>">
  </form>
