  <h1><?php echo $this->escape($this->title);?></h1>
  <div id="description">
    <?php echo $this->escape($this->description);?>
  </div>
  <form name="register" method="post" action="<?php echo $this->escape($this->action)?>">
  <table>
    <tr>
	  <td><?php echo $this->escape($this->label_uname)?></td>
	  <td><input type="text" name="username"></td>
	</tr>
    <tr>
	  <td><?php echo $this->escape($this->label_fname)?></td>
	  <td><input type="text" name=firstname></td>
	</tr>	
	 <tr>
	  <td><?php echo $this->escape($this->label_lname)?></td>
	  <td><input type="text" name="lastname"></td>
	</tr>
    <tr>
	  <td><?php echo $this->escape($this->label_pass)?></td>
	  <td><input type="password" name="password"></td>
	</tr>	
  </table>
  <input type="submit" name="submit" value="<?php echo $this->escape($this->label_submit);?>">
  </form>
